### ISSUE TITLE
add admin user

### ISSUE THREAD

**Issue by kmezhoud** [HemabhKamboj/Pizza-ordering-app#6]
Dear @HemabhKamboj ,
Thank you for sharing your code.
I am newbie with Python, and I am leaning Django framework.
I am interesting particularly to develop web app to manage orders from customers and manage stock of items in shops.
I found your Pizza app which is a good starting project.  I would like to manage `menus`.
How can I add admin user?
Thanks
Karim

**Comment by HemabhKamboj** [comment]
Hi @kmezhoud , happy to know that this small project is of any use to someone.


Adding admin user.

As described in step no. 5 of installation, on running the following command
`python manage.py createsuper`

You will be prompted to create a admin user.
Once your installation is complete and your django server is up and running, you can visit the route 
`/admin`

and enter the django admin panel by entering admin creds which you created while running the python manage.py createsuper command.


Hope this solves your query?

**Comment by kmezhoud** [comment]
@HemabhKamboj  Thanks,
I am getting an issue at this step:
```
(venv) Mezhoud@kirus Pizza-ordering-app % python manage.py createsuper 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'createsuper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/DATA/learn_by_example/order/Pizza-ordering-app/pizza/settings.py", line 14, in <module>
    import django_heroku
ModuleNotFoundError: No module named 'django_heroku'
```
I changed in `requiement.txt` file `django-heroku==0.3.1` by `django_heroku==0.3.1`

and rerun the step 4:
```
(venv) Mezhoud@kirus Pizza-ordering-app % pip3 install -r requirements.txt
Requirement already satisfied: certifi==2019.3.9 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (2019.3.9)
Requirement already satisfied: chardet==3.0.4 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: dj-database-url==0.5.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (0.5.0)
Requirement already satisfied: Django==2.2.10 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.2.10)
Requirement already satisfied: django_heroku==0.3.1 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.3.1)
Requirement already satisfied: gunicorn==19.9.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 6)) (19.9.0)
Requirement already satisfied: idna==2.8 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 7)) (2.8)
Requirement already satisfied: psycopg2==2.7.7 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 8)) (2.7.7)
Requirement already satisfied: pytz==2018.9 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 9)) (2018.9)
Requirement already satisfied: requests==2.21.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 10)) (2.21.0)
Requirement already satisfied: stripe==2.21.0 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 11)) (2.21.0)
Requirement already satisfied: urllib3==1.24.2 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 12)) (1.24.2)
Requirement already satisfied: whitenoise==4.1.2 in ./venv/lib/python3.7/site-packages (from -r requirements.txt (line 13)) (4.1.2)
Requirement already satisfied: sqlparse in ./venv/lib/python3.7/site-packages (from Django==2.2.10->-r requirements.txt (line 4)) (0.3.1)

```
Django_heroku seems to be installed. But When I rerun step 5, I got the same error message:

```
(venv) Mezhoud@kirus Pizza-ordering-app % python manage.py createsuper
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 224, in fetch_command
    app_name = commands[subcommand]
KeyError: 'createsuper'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 231, in fetch_command
    settings.INSTALLED_APPS
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Volumes/DATA/learn_by_example/order/Pizza-ordering-app/pizza/settings.py", line 14, in <module>
    import django_heroku
ModuleNotFoundError: No module named 'django_heroku'
(venv) Mezhoud@kirus Pizza-ordering-app % 

```

**Comment by kmezhoud** [comment]
any way. 
I used Spyder and rerun all steps, until step 5

```


python manage.py createsuper
Unknown command: 'createsuper'. Did you mean createsuperuser?
Type 'manage.py help' for usage.

!python manage.py createsuperuser

You have 3 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth.
Run 'python manage.py migrate' to apply them.

Username (leave blank to use 'mezhoud
```
I run:
```
!python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, orders, sessions
Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK

!python manage.py createsuperuser
Username (leave blank to use 'mezhoud'): 
```
And then the app is frozen at this step.
I did not note `/admin` folder?
How can I  `and enter the django admin panel by entering admin creds which you created while running the python manage.py createsuper command.` ?

Thanks!

**Comment by HemabhKamboj** [comment]
@kmezhoud my apologies,
the command is 

`python manage.py createsuperuser`

the app is frozen post this step as it is asking you to enter  a username. if you dont enter any username and just press enter it will make your username as `mezhoud`

post entering username, it will ask you to enter a password.

The password might not be shown while entering.


Also `/admin` is not a folder. its a route.
By route I mean that if your django server is running at `localhost:8080` ,
so you will have to visit 
`localhost:8080/admin` in your web browser

**Comment by kmezhoud** [comment]
It works!
Many Thanks!
Karim
